/*
Dynamicdns.pro

Testing SubdomainAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dynamicdnsapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_dynamicdnsapi_SubdomainAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SubdomainAPIService Updateip", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var subdomain string

		resp, httpRes, err := apiClient.SubdomainAPI.Updateip(context.Background(), subdomain).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
