/*
Dynamicdns.pro

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dynamicdnsapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Update400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Update400Response{}

// Update400Response struct for Update400Response
type Update400Response struct {
	// Error overview.
	Message string `json:"message"`
}

type _Update400Response Update400Response

// NewUpdate400Response instantiates a new Update400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdate400Response(message string) *Update400Response {
	this := Update400Response{}
	this.Message = message
	return &this
}

// NewUpdate400ResponseWithDefaults instantiates a new Update400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdate400ResponseWithDefaults() *Update400Response {
	this := Update400Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *Update400Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *Update400Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *Update400Response) SetMessage(v string) {
	o.Message = v
}

func (o Update400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Update400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *Update400Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdate400Response := _Update400Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdate400Response)

	if err != nil {
		return err
	}

	*o = Update400Response(varUpdate400Response)

	return err
}

type NullableUpdate400Response struct {
	value *Update400Response
	isSet bool
}

func (v NullableUpdate400Response) Get() *Update400Response {
	return v.value
}

func (v *NullableUpdate400Response) Set(val *Update400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdate400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdate400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdate400Response(val *Update400Response) *NullableUpdate400Response {
	return &NullableUpdate400Response{value: val, isSet: true}
}

func (v NullableUpdate400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdate400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


