/*
Dynamicdns.pro

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dynamicdnsapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Updateip403Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Updateip403Response{}

// Updateip403Response struct for Updateip403Response
type Updateip403Response struct {
	// Error overview.
	Message string `json:"message"`
}

type _Updateip403Response Updateip403Response

// NewUpdateip403Response instantiates a new Updateip403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateip403Response(message string) *Updateip403Response {
	this := Updateip403Response{}
	this.Message = message
	return &this
}

// NewUpdateip403ResponseWithDefaults instantiates a new Updateip403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateip403ResponseWithDefaults() *Updateip403Response {
	this := Updateip403Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *Updateip403Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *Updateip403Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *Updateip403Response) SetMessage(v string) {
	o.Message = v
}

func (o Updateip403Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Updateip403Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *Updateip403Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateip403Response := _Updateip403Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateip403Response)

	if err != nil {
		return err
	}

	*o = Updateip403Response(varUpdateip403Response)

	return err
}

type NullableUpdateip403Response struct {
	value *Updateip403Response
	isSet bool
}

func (v NullableUpdateip403Response) Get() *Updateip403Response {
	return v.value
}

func (v *NullableUpdateip403Response) Set(val *Updateip403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateip403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateip403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateip403Response(val *Updateip403Response) *NullableUpdateip403Response {
	return &NullableUpdateip403Response{value: val, isSet: true}
}

func (v NullableUpdateip403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateip403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


